// Generated by CoffeeScript 1.6.2
(function() {
  var checkLogin, db;

  db = require('../database');

  exports.any = function(req, res, next) {
    return checkLogin(req, res, next, 0);
  };

  exports.login.get = function(req, res, next) {
    return checkLogin(req, res, next, -1);
  };

  exports.login.post = function(req, res, next) {
    if (!checkLogin(req, res, next, -1)) {
      return db.users.findOne;
    } else {
      return res.redirect('/');
    }
  };

  exports.logout = function(req, res, next) {
    req.session.destroy();
    return res.redirect('/');
  };

  exports.more = function(req, res, next) {
    return checkLogin(req, res, next, 1);
  };

  exports.staff = function(req, res, next) {
    return checkLogin(req, res, next, 2);
  };

  checkLogin = function(req, res, next, level) {
    var msg;

    if (req.session.user) {
      return db.users.findOne({
        _id: req.session.user._id
      }, {
        password: 0
      }, function(err, resp) {
        if (err) {

        } else if (resp) {
          req.session.user = resp;
          switch (level) {
            case 2:
              if (resp.isStaff) {
                return next();
              } else {
                return res.redirect('back', {
                  error: 'You must be a staff member to see this page.'
                });
              }
              break;
            case -1:
              return true;
            default:
              return next();
          }
        } else {
          return res.redirect('/logout');
        }
      });
    } else {
      switch (level) {
        case 0:
          return next();
        case -1:
          return false;
        default:
          if (level === 2) {
            msg = 'You must be a staff member and logged in to see this page.';
          } else {
            msg = 'You must be logged in to see this page';
          }
          return res.redirect('back', {
            error: msg
          });
      }
    }
  };

}).call(this);
