// Generated by CoffeeScript 1.6.2
(function() {
  var db;

  db = require('../db');

  exports.optionalLogin = function(req, res, next) {
    if (req.session.user) {
      return db.Users.findOne({
        _id: req.session.user._id
      }, {
        password: 0
      }, function(err, resp) {
        if (!err) {
          if (resp) {
            req.session.isUser = true;
            if (resp.isStaff) {
              req.session.isStaff = true;
            } else {
              req.session.isStaff = false;
            }
            req.session.user = resp;
            return next();
          } else {
            return res.redirect('/logout');
          }
        } else {
          console.log("Error (auth): " + err);
          return res.end(JSON.stringify(err));
        }
      });
    } else {
      req.session.isUser = false;
      return next();
    }
  };

  exports.requireStaff = function(req, res, next) {
    if (req.session.user) {
      return db.Users.findOne({
        _id: req.session.user._id
      }, {
        password: 0
      }, function(err, resp) {
        if (!err) {
          if (resp) {
            req.session.isUser = true;
            if (resp.isStaff) {
              req.session.isStaff = true;
            } else {
              req.session.isStaff = false;
            }
            req.session.user = resp;
            return next();
          } else {
            return res.redirect('/logout');
          }
        } else {
          console.log("Error (auth): " + err);
          return res.end(JSON.stringify(err));
        }
      });
    } else {
      return res.redirect('/login');
    }
  };

  exports.login_get = function(req, res, next) {
    if (req.session.message) {
      res.render('login', req.session.message);
      return req.session.message = null;
    } else {
      return res.render('login');
    }
  };

  exports.login_post = function(req, res, next) {
    var err;

    err = [];
    if (!req.body.username) {
      err.push('Username reqired.');
    }
    if (!req.body.password || req.body.password.length < 10) {
      err.push('Password must be ten characters or longer.');
    }
    if (err.length > 0) {
      req.session.message = req.body;
      req.session.message._err = err;
      return res.redirect('/login');
    } else {
      return db.Users.findOne({
        username: req.body.username
      }, function(err, resp) {
        if (!err) {
          if (resp) {
            return resp.comparePassword(req.body.password, function(err, isMatch) {
              if (!err) {
                if (isMatch) {
                  req.session.user = resp;
                  req.session.isUser = true;
                  if (resp.isStaff) {
                    req.session.isStaff = true;
                    return res.redirect('/staff/');
                  } else {
                    req.session.isStaff = false;
                    return res.redirect('/');
                  }
                } else {
                  req.session.message = req.body;
                  req.session.message._err = ["Invalid password"];
                  return res.redirect('/login');
                }
              } else {
                console.log("Error (auth): " + err);
                return res.end(JSON.stringify(err));
              }
            });
          } else {
            req.session.message = req.body;
            req.session.message._err = ["Invalid username"];
            return res.redirect('/login');
          }
        } else {
          console.log("Error (auth): " + err);
          return res.end(JSON.stringify(err));
        }
      });
    }
  };

  exports.logout = function(req, res, next) {
    req.session.destroy();
    return res.redirect('/');
  };

}).call(this);
