// Generated by CoffeeScript 1.6.2
(function() {
  var db;

  db = require('../db');

  module.exports = function(callback) {
    var dummy;

    dummy = {
      name: "Webmaster Smith",
      username: "webby",
      password: "Change me. Ha."
    };
    return db.Users.findOne({
      username: dummy.username
    }, function(err, resp) {
      if (err) {
        return callback(err);
      } else if (resp) {
        return callback("You have already completed the setup. You do not need to run this again.");
      } else {
        return new db.Users({
          username: dummy.username,
          name: dummy.name,
          bio: {
            rendered: null,
            notRendered: null
          },
          email: dummy.email || ("" + (dummy.name.toLowerCase().replace(' ', '.')) + "@pineviewtorch.com"),
          isStaff: true,
          password: dummy.password,
          permissions: {
            knowsHTML: true,
            canPublishStories: true,
            canDeletePhotos: true,
            canManageIssues: true,
            canManageUsers: true,
            canManageSections: true,
            canEditPlannerFormats: true,
            canAcceptPlanners: true,
            canEditOthersComments: true,
            canComment: true,
            canChat: true,
            accountStatus: {
              isWebmaster: true,
              isRetired: false,
              isDisabled: false
            }
          }
        }).save(function(err) {
          var sectionErrs;

          if (err) {
            return callback(err);
          } else {
            sectionErrs = 0;
            if (sectionErrs > 0) {
              return callback("The setup was completed successfully. You may now run the production server.");
            } else {
              return callback(err);
            }
          }
        });
      }
    });
  };

}).call(this);
