// Generated by CoffeeScript 1.6.3
(function() {
  var client, elasticsearch;

  elasticsearch = require('elasticsearch');

  client = new elasticsearch.Client({
    hosts: 'localhost:9200'
  });

  module.exports = client;

}).call(this);
